### ISSUE TITLE
Alarm help page links to audio-joiner

### ISSUE THREAD

**Issue by jbrown123** [brian-girko/alarm#1]
Your alarm page at https://add0n.com/alarm.html has github links to your audio joiner project instead of to this one. You might want to change those. Looks like a copy-paste error.

For example, under "Need Help" you have this:

To report more bugs or submit a new bug please visit https://github.com/brian-girko/audio-joiner/

**Comment by brian-girko** [comment]
Thanks! It is fixed. It might take some time for the changes to apply.
