### ISSUE TITLE
Sort alarms by time

### ISSUE THREAD

**Issue by nicolasff** [brian-girko/alarm#4]
Thanks for making this extension, and for publishing the code on Github!

I'd like to make a suggestion for a feature that I haven't seen so far: it would be great if alarms could be ordered by time. I find that as I add more than a handful it becomes an O(N) scan through all of them to find one (since only 3-4 can be displayed in the restricted pop-up) and it would be easier if they were kept in order.

As a workaround, I use *Inspect element* on the extension, navigate to the Console, and run:
```javascript
function getTime(t) { return t.hours * 60 + t.minutes; }
function cmpTime(a, b) {
  const at = getTime(a.time);
  const bt = getTime(b.time);
  return (at < bt ? -1 : at > bt ? 1 : 0);
}
chrome.storage.local.get('alarms', function(res) {
  const sorted = res.alarms.sort(cmpTime);
  chrome.storage.local.set({alarms: sorted}, out => console.log('Sorted', sorted.length, 'alarms'));
});
```
Which re-orders them by time.

This could also be an option in the settings.

**Comment by brian-girko** [comment]
@nicolasff thanks for the report.

**Comment by nicolasff** [comment]
@brian-girko awesome, thanks for the quick fix!
