### ISSUE TITLE
[Feature Request] Using the extension outside of browser

### ISSUE THREAD

**Issue by chromer030** [brian-girko/alarm#7]
Thank you for this great and useful extension , please implement an option for opening the extension in a new separate pop-op window. will be much more usable and in operating systems like Chrome OS , user will be able to use it all the time not just in browser and when browser is in front.

Like this extension : 

![Screenshot_20210602_053445](https://user-images.githubusercontent.com/13361552/120429367-cdb0e400-c364-11eb-9222-7195d5e8c978.jpg)

Thanks a million.

**Comment by brian-girko** [comment]
Do you need to open the interface with a keyboard shortcut (so that you can assign a global shortcut for this extension to open its interface)? or you would like to have an option so that clicking on the browser action opens the interface on its window

**Comment by chromer030** [comment]
>> clicking on the browser action opens the interface on its window.

This feature as an optional option would be great.
Thank you again.

**Comment by brian-girko** [comment]
On the v0.1.7 release, you can do both. Either use the options page to alter the action behavior or go to chrome://extensions/shortcuts to define a custom shortcut.

**Comment by chromer030** [comment]
Tested new release in both Linux and Chrome OS , working nicely. Thank you very much.
Chrome OS :
![Screenshot_20210602_145053](https://user-images.githubusercontent.com/13361552/120503173-95d08d80-c3b2-11eb-9c40-e25ab7f9b4fa.jpg)

Linux : 
![Screenshot_20210602_144817](https://user-images.githubusercontent.com/13361552/120503237-a41ea980-c3b2-11eb-9cec-31c8ab833956.jpg)
